kind: Pod
apiVersion: v1
metadata:
  name: firstpod
  labels:
    app: fp
    released: stable
    team: red
  annotations:
    logDir: "etc/logs"
spec:
  containers:
    - name: db
      image: redis
    - name: web
      image: httpd