version: "3.9"
services:
  flightservice:
    container_name: flightservice
    image: flightservice
    restart: on-failure
    ports:
      - "19092:9092"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-flightdb
  simpleservice:
    container_name: simpleservice
    image: simpleservice
    ports:
      - "19093:9093"
  docker-flightdb:
    container_name: docker-flightdb
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: reservation
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=test1234 --execute \"SHOW DATABASES\""
      interval: 4s
      timeout: 20s
      retries: 5
