version: "3.9"
services:
  productservice:
    container_name: productservice
    image: productservice
    restart: on-failure
    ports:
      - "19090:9090"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - couponservice
      - docker-mysql
  couponservice:
    container_name: couponservice
    image: couponservice
    restart: on-failure
    ports:
      - "19091:9091"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
  simpleservice:
    container_name: simpleservice
    image: simpleservice
    ports:
      - "19093:9093"
  docker-mysql:
    container_name: docker-mysql
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=test1234 --execute \"SHOW DATABASES\""
      interval: 4s
      timeout: 20s
      retries: 5
